### ISSUE TITLE
Add A VATSIM Network Site

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/afv-beta#4]
To be positioned in a sticky footer at the bottom of the page, centred, in a similar style to the one found on the CTP website (as below).

<img width="2410" alt="Screenshot 2019-03-10 at 20 02 18" src="https://user-images.githubusercontent.com/7726792/54090759-a0388400-436f-11e9-82ec-8c1e74123efe.png">

**Comment by AxonC** [comment]
Resolved by #10
